# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    sesionservice:
        class: AppBundle\Service\SesionService
        arguments: ['@doctrine.orm.entity_manager']
        
        
    bitacoraservice:
        class: AppBundle\Service\BitacoraService
        arguments: ['@doctrine.orm.entity_manager']

    conexionfoxservice:
        class: AppBundle\Service\ConexionFoxService
    
    notificacionesservice:
        class: AppBundle\Service\NotificacionesService
        arguments: ['@mailer','@templating']